version: '2'
services:
    muturama-app:
        image: muturama
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://muturama-mysql:3306/muturama?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    muturama-mysql:
        extends:
            file: mysql.yml
            service: muturama-mysql
